
export const WORD_POOL = [
  "about", "above", "across", "action", "added", "after", "again", "against", "alive", "almost", 
  "alone", "along", "already", "also", "always", "among", "amount", "ancient", "angry", "animal", 
  "another", "answer", "anybody", "anyone", "anything", "anyway", "anywhere", "appear", "apple", 
  "applied", "approach", "april", "area", "argue", "around", "arrive", "article", "aside", "asked", 
  "asleep", "aspect", "assumed", "attack", "attention", "august", "author", "average", "avoid", 
  "awake", "aware", "away", "awful", "baby", "back", "badly", "bag", "ball", "bank", "bar", 
  "base", "basic", "basis", "basket", "battle", "beach", "bear", "beat", "beautiful", "beauty", 
  "became", "because", "become", "becoming", "bedroom", "been", "before", "began", "begin", 
  "beginning", "begun", "behave", "behind", "being", "belief", "believe", "bell", "belong", "below", 
  "beside", "besides", "best", "better", "between", "beyond", "bicycle", "bigger", "biggest", "bill", 
  "birds", "birth", "birthday", "bitter", "black", "blank", "block", "blood", "blow", "blue", 
  "board", "boat", "body", "bone", "book", "born", "both", "bottle", "bottom", "bought", 
  "bowl", "box", "boy", "brain", "branch", "brass", "brave", "bread", "break", "breakfast", 
  "breath", "breathe", "breathing", "breeze", "bridge", "brief", "bright", "bring", "broad", "broke", 
  "broken", "brother", "brought", "brown", "brush", "bucket", "build", "building", "built", "burn", 
  "burst", "bus", "bush", "business", "busy", "butter", "button", "buy", "cabin", "cage", 
  "cake", "call", "called", "calling", "calm", "came", "camera", "camp", "can", "canal", 
  "candle", "cannot", "cap", "capital", "captain", "captured", "car", "card", "care", "careful", 
  "carefully", "carried", "carry", "case", "cast", "castle", "cat", "catch", "cattle", "caught", 
  "cause", "cave", "cell", "cent", "center", "central", "century", "certain", "certainly", "chain", 
  "chair", "chamber", "chance", "change", "changing", "chapter", "character", "charge", "chart", "check", 
  "cheese", "chemical", "chest", "chicken", "chief", "child", "children", "choice", "choose", "chose", 
  "chosen", "church", "circle", "circus", "citizen", "city", "class", "classroom", "clay", "clean", 
  "clear", "clearly", "climb", "clock", "close", "closely", "closer", "cloth", "clothes", "cloud", 
  "club", "coach", "coal", "coast", "coat", "coffee", "cold", "collect", "college", "colony", 
  "color", "column", "combination", "combine", "come", "comfortable", "coming", "command", "common", "community", 
  "company", "compare", "compass", "complete", "completely", "complex", "composed", "composition", "compound", "concerned", 
  "condition", "congress", "connected", "consider", "consist", "consonant", "constantly", "construction", "contain", "continent", 
  "continued", "contrast", "control", "conversation", "cook", "cookies", "cool", "copper", "copy", "corn", 
  "corner", "correct", "correctly", "cost", "cotton", "could", "count", "country", "couple", "c